# Generated by Django 6.0.4 on 2026-05-09 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialAppApp", "0006_post_edited_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.CharField(blank=True, max_length=100)),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("freshman", "Freshman"),
                            ("sophomore", "Sophomore"),
                            ("junior", "Junior"),
                            ("senior", "Senior"),
                            ("graduate", "Graduate"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("research_interests", models.CharField(blank=True, max_length=300)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
